#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/shitakamiyamato/development/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/shitakamiyamato/Desktop/ble_beacon_appのコピー9行動データまで"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/shitakamiyamato/Desktop/ble_beacon_appのコピー9行動データまで/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "FLUTTER_CLI_BUILD_MODE=debug"
export "DART_DEFINES=RkxVVFRFUl9WRVJTSU9OPTMuMzQuMC0wLjAucHJl,RkxVVFRFUl9DSEFOTkVMPWJldGE=,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049MDFmZGU5NTZmMA==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049OGVkOWVkYmQ3YQ==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My45LjAgKGJ1aWxkIDMuOS4wLTE5Ni4xLmJldGEp"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/shitakamiyamato/Desktop/ble_beacon_appのコピー9行動データまで/.dart_tool/package_config.json"
